### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by guilherme6191** [vivek12345/React-16---Error-Boundaries#1]
Hey @vivek12345, thanks for the content.

I have a question about how you structured your code if it's ok.

https://github.com/vivek12345/React-16---Error-Boundaries/blob/a3cbe17797ca84f513c43a6da25baad27561c877/components/ProductList.js#L35

Why wrap every `Product` with the `ErrorBoundary` component instead of wrapping the whole result in the `render` method? Eg:
```
<div className="productList" style={{ marginTop: '40px' }}>
<ErrorBoundary name="productsList">
    { this.renderProducts() }
</ErrorBoundary>
 </div>
```
Is it for more specific error log if we wanted to use the name prop for logging?

**Comment by vivek12345** [comment]
@guilherme6191 Yes I would be very happy to answer any questions you have.
So in order to answer your question of why I wrapped every Product with the ErrorBoundary component instead of wrapping the whole result in the render method?

It's done because:-
A) The lifecycle hook componentDidCatch can be on the parent component only which in this case is named as ErrorBoundary.
B) Had the code been written in this way:-
```
<ErrorBoundary name="productsList">
    { this.renderProducts() }
</ErrorBoundary>

```
If any of the product would have failed to render, then the entire catalog of products would have been replaced with the fallback ui defined inside ErrorBoundary.

Wrapping every product gives me the advantage where in even if one product fails to render at any point, the other product's continue to be shown with only the erroneous product being shown with a fallback UI.  

With the current implementation this is how the UI would look, if any of the product fails to render:-
<img width="1279" alt="screen shot 2018-02-15 at 3 21 47 am" src="https://user-images.githubusercontent.com/4931048/36230205-a9316876-11ff-11e8-9429-fc8708a1d219.png">

But If I will wrap the entire thing inside ErrorBoundary, the UI would be something like this:-
<img width="1280" alt="screen shot 2018-02-15 at 3 21 17 am" src="https://user-images.githubusercontent.com/4931048/36230241-c8fbbeb8-11ff-11e8-84ed-926ff44c4cc8.png">




I hope I was able to explain well, in case their is still some confusion, I would try and prepare a codesandbox link for you which would better explain both the scenarios.

**Comment by guilherme6191** [comment]
Perfect, @vivek12345. I got my answer.

Totally makes sense to have the rest of the UI working so the User can get some content. It's a better experience than breaking the whole thing though it's just a small part that broke.

Thanks for the thorough answer, mate.
